/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ru.avem.resonance

import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test

class AppTest {
    @Test
    fun testAppHasAGreeting() {
        val classUnderTest = Main()
        assertNotNull(classUnderTest, "app should have a greeting")
    }
}
